In [5]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
df=sns.load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [4]:
X = df[['carat', 'depth', 'table', 'price', 'x', 'y', 'z']]
y = df[['cut', 'color', 'clarity']]

In [7]:
for col in y.columns:
    le = LabelEncoder()
    y[col]=le.fit_transform(y[col])

C:\Users\aayus\AppData\Local\Temp\ipykernel_20236\3532092453.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[col]=le.fit_transform(y[col])
C:\Users\aayus\AppData\Local\Temp\ipykernel_20236\3532092453.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[col]=le.fit_transform(y[col])
C:\Users\aayus\AppData\Local\Temp\ipykernel_20236\3532092453.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[col]=le.fit_transform(y[col])

In [ ]:
y.head()

   cut  color  clarity
0    2      1        3
1    3      1        2
2    1      1        4
3    3      5        5
4    1      6        3

In [ ]:
X = df[['carat', 'depth', 'table', 'price', 'x', 'y', 'z']]
y = df[['cut', 'color', 'clarity']]

In [ ]:
for cols in ['color','clarity']:
    le=LabelEncoder()
    dia[cols]=le.fit_transform(dia[cols])

np.random.seed(43)
ran=np.random.choice(dia.index, size=int(0.91*len(dia)), replace=False)
print(dia.info())

scaler=MinMaxScaler()
columns_for_norm=['depth','table','price','x','y','z']
dia_norm=pd.DataFrame(scaler.fit_transform(dia[columns_for_norm]), columns=columns_for_norm)


#Original Data Summ
print("\nOriginal Data Summ\n")
print(dia.describe())
print("\nNormalised Data Summ\n")
print(dia_norm.describe())


#columns_for_training=['depth','x','y','z']
dia_train=dia_norm.loc[ran,:]
dia_test=dia_norm.drop(ran)
dia_target_cat=dia.iloc[ran, 1]
dia_test_cat=dia.drop(ran)['cut']

#KNN
knn=KNeighborsClassifier(n_neighbors=32,metric='manhattan')
knn.fit(dia_train, dia_target_cat)
pr=knn.predict(dia_test)

#Confusion Matrix
matrix1=confusion_matrix(dia_test_cat, pr)
print("\nConfusion Matrix\n",matrix1)


#Accuracy Score
ac1=accuracy_score(dia_test_cat, pr)*100
print("\nAccuracy: {:.2f}".format(ac1))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB
None
              carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000
mean       0.797940     61.749405     57.457184   3932.799722      5.731157
std        0.474011      1.432621      2.234491   3989.439738      1.121761
min        0.200000     43.000000     43.000000    326.000000      0.000000
25%        0.400000     61.000000     56.000000    950.000000      4.710000
50%        0.700000     61.800000     57.000000   2401.000000      5.700000
75%        1.040000     62.500000     59.000000   5324.250000      6.540000
max        5.010000     79.000000     95.000000  18823.000000     10.740000

                  y             z
count  53940.000000  53940.000000
mean       5.734526      3.538734
std        1.142135      0.705699
min        0.000000      0.000000
25%        4.720000      2.910000
50%        5.710000      3.530000
75%        6.540000      4.040000
max       58.900000     31.800000
   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  int64
 3   clarity  53940 non-null  int64
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(1), float64(6), int64(3)
memory usage: 3.8 MB
None

Original Data Summ

              carat         color       clarity         depth         table  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000
mean       0.797940      2.594197      3.835150     61.749405     57.457184
std        0.474011      1.701105      1.724591      1.432621      2.234491
min        0.200000      0.000000      0.000000     43.000000     43.000000
25%        0.400000      1.000000      2.000000     61.000000     56.000000
50%        0.700000      3.000000      4.000000     61.800000     57.000000
75%        1.040000      4.000000      5.000000     62.500000     59.000000
max        5.010000      6.000000      7.000000     79.000000     95.000000

              price             x             y             z
count  53940.000000  53940.000000  53940.000000  53940.000000
mean    3932.799722      5.731157      5.734526      3.538734
std     3989.439738      1.121761      1.142135      0.705699
min      326.000000      0.000000      0.000000      0.000000
25%      950.000000      4.710000      4.720000      2.910000
50%     2401.000000      5.700000      5.710000      3.530000
75%     5324.250000      6.540000      6.540000      4.040000
max    18823.000000     10.740000     58.900000     31.800000

Normalised Data Summ

              depth         table         price             x             y  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000
mean       0.520817      0.278023      0.194994      0.533627      0.097360
std        0.039795      0.042971      0.215680      0.104447      0.019391
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.500000      0.250000      0.033735      0.438547      0.080136
50%        0.522222      0.269231      0.112180      0.530726      0.096944
75%        0.541667      0.307692      0.270219      0.608939      0.111036
max        1.000000      1.000000      1.000000      1.000000      1.000000

                  z
count  53940.000000
mean       0.111281
std        0.022192
min        0.000000
25%        0.091509
50%        0.111006
75%        0.127044
max        1.000000

Confusion Matrix
 [[  90   39    3    6    5]
 [   5  236   10   75  117]
 [   0    2 1816  105   33]
 [   0    4  144 1020   65]
 [   0   39  291  368  382]]

Accuracy: 73.00