In [9]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder

import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import cross_val_score

In [2]:
df_train= pd.read_csv('train.csv')
df_train.head()

,dur,proto,service,state,rate,sttl,dttl,sjit,djit,swin,...,dpkts_log1p,sloss_log1p,dloss_log1p,stcpb_log1p,dtcpb_log1p,response_body_len_log1p,sinpkt_log1p,dinpkt_log1p,sload_log1p,dload_log1p
0,0.121478,tcp,-,FIN,74.087490,252,254,30.177547,11.830604,2.0,...,1.609438,0.000000,0.000000,20.248085,21.512874,0.0,3.230630,2.238047,9.558172,9.047394
1,0.649902,tcp,-,FIN,78.473370,62,252,61.426933,1387.778300,2.0,...,3.663562,1.098612,2.890372,21.072432,21.847347,0.0,3.930158,2.799283,9.035524,13.129482
2,1.623129,tcp,-,FIN,14.170161,62,252,17179.586000,11420.926000,2.0,...,2.833213,0.693147,1.945910,21.472865,21.809507,0.0,5.450504,4.641861,7.360913,11.017485
3,1.681642,tcp,ftp,FIN,13.677108,62,252,259.080170,4991.784700,2.0,...,2.564949,0.693147,1.386294,20.825027,20.769618,0.0,5.036150,4.513446,7.916143,8.119584
4,0.449454,tcp,-,FIN,33.373825,254,252,2415.837600,115.807000,2.0,...,1.945910,1.098612,0.693147,21.613680,21.404924,0.0,3.886712,4.339375,9.055147,8.291060

In [3]:
df_test= pd.read_csv('test.csv')
df_test.head()

,dur,proto,service,state,rate,sttl,dttl,sjit,djit,swin,...,dpkts_log1p,sloss_log1p,dloss_log1p,stcpb_log1p,dtcpb_log1p,response_body_len_log1p,sinpkt_log1p,dinpkt_log1p,sload_log1p,dload_log1p
0,0.000011,udp,-,INT,90909.09,254,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.010940,0.0,19.010485,0.0
1,0.000008,udp,-,INT,125000.00,254,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.007968,0.0,20.596570,0.0
2,0.000005,udp,-,INT,200000.00,254,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.004988,0.0,20.565910,0.0
3,0.000006,udp,-,INT,166666.66,254,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.005982,0.0,20.212440,0.0
4,0.000010,udp,-,INT,100000.00,254,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.009950,0.0,20.561218,0.0

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 40 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   dur                      175341 non-null  float64
 1   proto                    175341 non-null  object
 2   service                  175341 non-null  object
 3   state                    175341 non-null  object
 4   rate                     175341 non-null  float64
 5   sttl                     175341 non-null  int64
 6   dttl                     175341 non-null  int64
 7   sjit                     175341 non-null  float64
 8   djit                     175341 non-null  float64
 9   swin                     175341 non-null  float64
 10  dwin                     175341 non-null  float64
 11  synack                   175341 non-null  float64
 12  ackdat                   175341 non-null  float64
 13  trans_depth              175341 non-null  int64
 14  ct_srv_src               175341 non-null  int64
 15  ct_state_ttl             175341 non-null  int64
 16  ct_dst_ltm               175341 non-null  int64
 17  ct_src_dport_ltm         175341 non-null  int64
 18  ct_dst_sport_ltm         175341 non-null  int64
 19  ct_dst_src_ltm           175341 non-null  int64
 20  ct_ftp_cmd               175341 non-null  int64
 21  ct_flw_http_mthd         175341 non-null  int64
 22  ct_src_ltm               175341 non-null  int64
 23  ct_srv_dst               175341 non-null  int64
 24  is_sm_ips_ports          175341 non-null  int64
 25  attack_cat               175341 non-null  object
 26  label                    175341 non-null  int64
 27  smean_log1p              175341 non-null  float64
 28  dmean_log1p              175341 non-null  float64
 29  spkts_log1p              175341 non-null  float64
 30  dpkts_log1p              175341 non-null  float64
 31  sloss_log1p              175341 non-null  float64
 32  dloss_log1p              175341 non-null  float64
 33  stcpb_log1p              175341 non-null  float64
 34  dtcpb_log1p              175341 non-null  float64
 35  response_body_len_log1p  175341 non-null  float64
 36  sinpkt_log1p             175341 non-null  float64
 37  dinpkt_log1p             175341 non-null  float64
 38  sload_log1p              175341 non-null  float64
 39  dload_log1p              175341 non-null  float64
dtypes: float64(21), int64(15), object(4)
memory usage: 53.5+ MB

🧹 Original dataset shape: (175341, 40)
✅ After removing duplicates: (105724, 40)
📊 Train shape: (84579, 39), Test shape: (21145, 39)
🔎 Overlapping samples between train & test: 0
🌲 RF Train Accuracy: 0.9957
🌲 RF Test Accuracy: 0.9963
🌲 RF OOB Score: 0.9946
✅ Encoded RF features shape: (84579, 2855)
Epoch 1/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9990 - loss: 0.0569 - val_accuracy: 1.0000 - val_loss: 0.0038
Epoch 2/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9999 - loss: 0.0059 - val_accuracy: 1.0000 - val_loss: 0.0026
Epoch 3/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 4/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9999 - loss: 0.0057 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 5/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 1.0000 - val_loss: 0.0024
Epoch 6/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 7/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 8/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9998 - loss: 0.0091 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 9/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9999 - loss: 0.0070 - val_accuracy: 1.0000 - val_loss: 0.0106
Epoch 10/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9998 - val_loss: 0.0028
Epoch 11/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 9.9288e-04
Epoch 12/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9998 - loss: 0.0094 - val_accuracy: 1.0000 - val_loss: 0.0029
Epoch 13/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 1.0000 - val_loss: 9.8011e-04
Epoch 14/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 15/15
661/661 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9998 - loss: 0.0121 - val_accuracy: 1.0000 - val_loss: 0.0031

🎯 Final Hybrid RF+DNN Test Accuracy: 1.0000
661/661 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step

📊 Confusion Matrix:
[[10329     0]
 [    0 10816]]

📄 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     10329
           1       1.00      1.00      1.00     10816

    accuracy                           1.00     21145
   macro avg       1.00      1.00      1.00     21145
weighted avg       1.00      1.00      1.00     21145