In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import cross_val_score

In [16]:
dfa=pd.read_csv("prepared_obs.csv")
dfb=pd.read_csv('prepared_plant2_obs.csv')
df_pest= pd.read_csv('prepared_pest_obs.csv')

In [4]:
dfa.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
5,315797416,2025/09/22 10:24 AM,53.015837,-1.217560,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
6,315889887,2025/09/22 9:49 AM,52.633048,-2.159995,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
7,315796359,2025-09-21 13:47:52,38.693507,-111.680819,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
8,315692619,2025-09-21 14:36:17,42.952977,-81.220301,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
9,315575227,2025-09-21 14:11:03,61.149895,-45.514545,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
10,315576254,2025-09-21 12:59:04,61.151178,-45.517288,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
11,315777458,2025-09-21 12:48:22,61.154564,-45.517339,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
12,315848241,2025-09-21 16:37:08,64.061917,24.519427,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
13,315581490,2025-09-21 12:16:07,61.149258,-45.514995,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
14,315613849,2025-09-21 13:22:54+01:00,52.045803,0.720892,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
15,315595331,2025-09-21 12:30:19+02:00,61.154842,-45.517208,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
16,315499597,2025-09-21 08:57:12,56.004232,-2.517871,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
17,315711373,2025-09-19 15:32:48-04:00,39.062970,-79.323775,Flowering,Achillea millefolium,common yarrow,52821,262,26.0
18,314760899,2025-09-18 08:32:58,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,261,15.0
19,314671810,2025-09-17 13:28:46,46.793167,-121.729866,Flowering,Achillea millefolium,common yarrow,52821,260,19.0
20,314881060,2025/09/17 11:33 AM,45.848500,-123.961264,Flowering,Achillea millefolium,common yarrow,52821,260,9.0
21,314877257,2025/09/17 11:32 AM,45.848278,-123.961350,Fruiting,Achillea millefolium,common yarrow,52821,260,9.0
22,314624633,2025-09-17 18:18:21,53.208419,-6.114972,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
23,314544453,2025-09-17 10:57:57,51.462255,-0.065373,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
24,314477944,2025-09-16 17:55:04,41.622425,-70.537878,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
25,314420251,2025-09-16 12:47:35-07:00,49.254517,-123.002242,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
26,314435157,2025-09-16 18:03:34,47.995943,7.833229,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
27,314343934,2025-09-16 16:44:04,65.034488,25.454223,Flowering,Achillea millefolium,common yarrow,52821,259,27.0
28,314279893,2025-09-16 06:23:51,51.532009,-0.286650,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
29,314242933,2025-09-15 18:47:19-04:00,39.725803,-76.076722,Flowering,Achillea millefolium,common yarrow,52821,258,14.0

In [5]:
dfb.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,299753119,2025-07-21 16:51:12,-39.434370,176.601988,Fruiting,Melicytus ramiflorus,Māhoe,197063,202,15.0
1,284940738,2025-05-29 08:38:15,-36.863667,174.803194,Flowering,Melicytus ramiflorus,Māhoe,197063,149,15.0
2,281118698,2025-05-11 14:06:12+12:00,-43.623842,172.638870,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
3,280156036,2025-05-11 13:45:12,-40.191279,176.135594,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
4,273582061,2025-04-26 11:16:37,-36.810763,174.943681,Flowering,Melicytus ramiflorus,Māhoe,197063,116,15.0
5,277585585,2025/04/26 10:05 AM,-43.579545,172.633167,Fruiting,Melicytus ramiflorus,Māhoe,197063,116,15.0
6,272136460,2025-04-22 17:13:17,-43.619107,172.650201,Fruiting,Melicytus ramiflorus,Māhoe,197063,112,15.0
7,272034640,2025-04-21 21:10:51,-38.517022,175.582863,Fruiting,Melicytus ramiflorus,Māhoe,197063,111,15.0
8,279300214,2025-04-18 12:45:40,-41.298378,174.010819,Fruiting,Melicytus ramiflorus,Māhoe,197063,108,15.0
9,277671049,2025-04-06 14:15:39+12:00,-45.842037,170.660478,Fruiting,Melicytus ramiflorus,Māhoe,197063,96,15.0
10,265513026,2025-03-16 14:02:45+13:00,-38.516995,175.582903,Fruiting,Melicytus ramiflorus,Māhoe,197063,75,15.0
11,266063589,2025/03/16 12:53 PM,-43.701831,172.698258,Flowering,Melicytus ramiflorus,Māhoe,197063,75,15.0
12,265325651,2025-03-15 10:42:15+13:00,-43.610250,172.642307,Fruiting,Melicytus ramiflorus,Māhoe,197063,73,15.0
13,264877164,2025-03-11 09:18:24+13:00,-40.729103,172.672438,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
14,264754904,2025-03-10 15:10:52+13:00,-43.627333,172.730255,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
15,264856087,2025/03/10 1:30 PM,-41.430072,172.995075,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
16,265363303,2025/03/09 2:31 PM,-43.784035,172.834154,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
17,265027851,2025-03-09 12:24:25,-41.105044,175.078232,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
18,264709531,2025/03/09 10:55 AM,-43.649333,172.769439,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
19,264331153,2025-03-04 09:39:54+13:00,-40.992080,173.012039,Fruiting,Melicytus ramiflorus,Māhoe,197063,62,15.0
20,263589406,2025-03-02 16:50:17,-41.334454,173.054780,Fruiting,Melicytus ramiflorus,Māhoe,197063,61,15.0
21,263587253,2025-03-02 12:08:41,-41.275132,173.731710,Fruiting,Melicytus ramiflorus,Māhoe,197063,61,15.0
22,267803871,2025/03/01 3:08 PM,-43.667441,172.788682,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
23,263448520,2025-03-01 13:34:14,-41.318110,174.204163,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
24,263799004,2025-03-01 10:25:53,-40.956967,173.059097,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
25,288834336,2025/02/27 22:18,-40.851206,172.824000,Fruiting,Melicytus ramiflorus,Māhoe,197063,58,15.0
26,263118759,2025/02/26 4:11 PM,-41.240185,174.944166,Flowering,Melicytus ramiflorus,Māhoe,197063,57,15.0
27,263029257,2025-02-25 16:11:45+13:00,-43.524462,172.655930,Fruiting,Melicytus ramiflorus,Māhoe,197063,56,15.0
28,263029424,2025-02-25 15:48:14+13:00,-43.524478,172.655900,Fruiting,Melicytus ramiflorus,Māhoe,197063,56,15.0
29,261940788,2025-02-17 13:24:28,-37.245290,175.819730,Fruiting,Melicytus ramiflorus,Māhoe,197063,48,15.0

In [29]:
# mergeing the two data sets 
plant = pd.concat([dfa,dfb], axis=0, ignore_index=True)
plant.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0

In [32]:
plant.shape

(758759, 10)

In [31]:
import pandas as pd
import re

# Example: ensure column is string
plant['observed_on'] = plant['observed_on'].astype(str)

# Extract only the date portion using regex
plant['observed_on'] = plant['observed_on'].apply(
    lambda x: re.search(r'\d{4}[-/]\d{2}[-/]\d{2}', x).group(0) if re.search(r'\d{4}[-/]\d{2}[-/]\d{2}', x) else x
)

# Standardize format (replace '/' with '-')
plant['observed_on'] = plant['observed_on'].str.replace('/', '-', regex=False)

In [ ]:
# Drop the temporary parsed column
plant.drop(columns='observed_on_parsed', inplace=True)

In [34]:
plant.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025-09-22,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
5,315797416,2025-09-22,53.015837,-1.217560,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
6,315889887,2025-09-22,52.633048,-2.159995,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
7,315796359,2025-09-21,38.693507,-111.680819,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
8,315692619,2025-09-21,42.952977,-81.220301,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
9,315575227,2025-09-21,61.149895,-45.514545,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
10,315576254,2025-09-21,61.151178,-45.517288,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
11,315777458,2025-09-21,61.154564,-45.517339,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
12,315848241,2025-09-21,64.061917,24.519427,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
13,315581490,2025-09-21,61.149258,-45.514995,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
14,315613849,2025-09-21,52.045803,0.720892,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
15,315595331,2025-09-21,61.154842,-45.517208,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
16,315499597,2025-09-21,56.004232,-2.517871,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
17,315711373,2025-09-19,39.062970,-79.323775,Flowering,Achillea millefolium,common yarrow,52821,262,26.0
18,314760899,2025-09-18,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,261,15.0
19,314671810,2025-09-17,46.793167,-121.729866,Flowering,Achillea millefolium,common yarrow,52821,260,19.0
20,314881060,2025-09-17,45.848500,-123.961264,Flowering,Achillea millefolium,common yarrow,52821,260,9.0
21,314877257,2025-09-17,45.848278,-123.961350,Fruiting,Achillea millefolium,common yarrow,52821,260,9.0
22,314624633,2025-09-17,53.208419,-6.114972,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
23,314544453,2025-09-17,51.462255,-0.065373,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
24,314477944,2025-09-16,41.622425,-70.537878,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
25,314420251,2025-09-16,49.254517,-123.002242,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
26,314435157,2025-09-16,47.995943,7.833229,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
27,314343934,2025-09-16,65.034488,25.454223,Flowering,Achillea millefolium,common yarrow,52821,259,27.0
28,314279893,2025-09-16,51.532009,-0.286650,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
29,314242933,2025-09-15,39.725803,-76.076722,Flowering,Achillea millefolium,common yarrow,52821,258,14.0

In [39]:
import numpy as np

conditions = [
    (plant['biome'].between(1, 5)),
    (plant['biome'].between(6, 8)),
    (plant['biome'].between(9, 14)),
    (plant['biome'].between(15, 21)),
    (plant['biome'].between(22, 24)),
    (plant['biome'] >= 25)
]

choices = ['A', 'B', 'C', 'D', 'E', 'H']

plant['biome_cat'] = np.select(conditions, choices, default='Unknown')

In [44]:
plant.head()

,observed_on,phenophase,scientific_name,common_name,doy,biome,biome_cat
0,2025-09-22,Flowering,Achillea millefolium,common yarrow,265,15.0,D
1,2025-09-22,Flowering,Achillea millefolium,common yarrow,265,15.0,D
2,2025-09-22,Flowering,Achillea millefolium,common yarrow,265,29.0,H
3,2025-09-22,Flowering,Achillea millefolium,common yarrow,265,15.0,D
4,2025-09-22,Flowering,Achillea millefolium,common yarrow,265,15.0,D

In [43]:
plant.drop(columns=['id','latitude','longitude','taxon_id'],inplace=True)

In [48]:
plant['doy'].head(20)

0     265
1     265
2     265
3     265
4     265
5     265
6     265
7     264
8     264
9     264
10    264
11    264
12    264
13    264
14    264
15    264
16    264
17    262
18    261
19    260
Name: doy, dtype: int64