In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import cross_val_score

In [3]:
dfa=pd.read_csv('prepared_obs.csv')
dfa.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0

In [9]:
dfa.shape

(597716, 10)

In [12]:
dfa.isnull().sum()

id                 0
observed_on        0
latitude           0
longitude          0
phenophase         0
scientific_name    0
common_name        0
taxon_id           0
doy                0
biome              0
dtype: int64

In [13]:
dfa['scientific_name'].nunique()

525

In [5]:
dfb=pd.read_csv('prepared_plant2_obs.csv')
dfb.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,299753119,2025-07-21 16:51:12,-39.434370,176.601988,Fruiting,Melicytus ramiflorus,Māhoe,197063,202,15.0
1,284940738,2025-05-29 08:38:15,-36.863667,174.803194,Flowering,Melicytus ramiflorus,Māhoe,197063,149,15.0
2,281118698,2025-05-11 14:06:12+12:00,-43.623842,172.638870,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
3,280156036,2025-05-11 13:45:12,-40.191279,176.135594,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
4,273582061,2025-04-26 11:16:37,-36.810763,174.943681,Flowering,Melicytus ramiflorus,Māhoe,197063,116,15.0

In [11]:
dfb.isnull().sum()

id                 0
observed_on        0
latitude           0
longitude          0
phenophase         0
scientific_name    0
common_name        0
taxon_id           0
doy                0
biome              0
dtype: int64

In [14]:
dfb['scientific_name'].nunique()

376

In [10]:
dfb.shape

(161043, 10)

In [15]:
flora = pd.concat([dfa,dfb], axis=0, ignore_index=True)
flora.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0

In [16]:
flora.shape

(758759, 10)

In [17]:
flora.to_csv("flora_dataset.csv", index=False)

In [7]:
df_pest = pd.read_csv('prepared_pest_obs.csv')
df_pest.head()

,id,observed_on,latitude,longitude,scientific_name,common_name,taxon_id,doy,biome
0,301225953,2025/07/01 8:35 AM,41.735947,-121.298850,Acyrthosiphon pisum,Pea Aphid,132882,182,7.0
1,279045138,2025/05/06 09:24,42.653488,2.845778,Acyrthosiphon pisum,Pea Aphid,132882,126,7.0
2,272452692,2025-04-23 09:48:51-05:00,27.782900,-97.561670,Acyrthosiphon pisum,Pea Aphid,132882,113,14.0
3,219194104,2024-05-29 13:54:36+02:00,40.583203,-4.151470,Acyrthosiphon pisum,Pea Aphid,132882,150,8.0
4,217965838,2024/05/24 6:32 PM,52.494606,13.326206,Acyrthosiphon pisum,Pea Aphid,132882,145,15.0

In [8]:
df_pest.shape

(72629, 9)