In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

import scipy.stats as stats
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [74]:

df_pest= pd.read_csv('enriched_prepared_pest_obs.csv')

In [76]:
df_pest['scientific_name'].nunique()

94

In [34]:
dfa.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
5,315797416,2025/09/22 10:24 AM,53.015837,-1.217560,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
6,315889887,2025/09/22 9:49 AM,52.633048,-2.159995,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
7,315796359,2025-09-21 13:47:52,38.693507,-111.680819,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
8,315692619,2025-09-21 14:36:17,42.952977,-81.220301,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
9,315575227,2025-09-21 14:11:03,61.149895,-45.514545,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
10,315576254,2025-09-21 12:59:04,61.151178,-45.517288,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
11,315777458,2025-09-21 12:48:22,61.154564,-45.517339,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
12,315848241,2025-09-21 16:37:08,64.061917,24.519427,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
13,315581490,2025-09-21 12:16:07,61.149258,-45.514995,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
14,315613849,2025-09-21 13:22:54+01:00,52.045803,0.720892,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
15,315595331,2025-09-21 12:30:19+02:00,61.154842,-45.517208,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
16,315499597,2025-09-21 08:57:12,56.004232,-2.517871,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
17,315711373,2025-09-19 15:32:48-04:00,39.062970,-79.323775,Flowering,Achillea millefolium,common yarrow,52821,262,26.0
18,314760899,2025-09-18 08:32:58,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,261,15.0
19,314671810,2025-09-17 13:28:46,46.793167,-121.729866,Flowering,Achillea millefolium,common yarrow,52821,260,19.0
20,314881060,2025/09/17 11:33 AM,45.848500,-123.961264,Flowering,Achillea millefolium,common yarrow,52821,260,9.0
21,314877257,2025/09/17 11:32 AM,45.848278,-123.961350,Fruiting,Achillea millefolium,common yarrow,52821,260,9.0
22,314624633,2025-09-17 18:18:21,53.208419,-6.114972,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
23,314544453,2025-09-17 10:57:57,51.462255,-0.065373,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
24,314477944,2025-09-16 17:55:04,41.622425,-70.537878,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
25,314420251,2025-09-16 12:47:35-07:00,49.254517,-123.002242,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
26,314435157,2025-09-16 18:03:34,47.995943,7.833229,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
27,314343934,2025-09-16 16:44:04,65.034488,25.454223,Flowering,Achillea millefolium,common yarrow,52821,259,27.0
28,314279893,2025-09-16 06:23:51,51.532009,-0.286650,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
29,314242933,2025-09-15 18:47:19-04:00,39.725803,-76.076722,Flowering,Achillea millefolium,common yarrow,52821,258,14.0

In [35]:
dfb.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,299753119,2025-07-21 16:51:12,-39.434370,176.601988,Fruiting,Melicytus ramiflorus,Māhoe,197063,202,15.0
1,284940738,2025-05-29 08:38:15,-36.863667,174.803194,Flowering,Melicytus ramiflorus,Māhoe,197063,149,15.0
2,281118698,2025-05-11 14:06:12+12:00,-43.623842,172.638870,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
3,280156036,2025-05-11 13:45:12,-40.191279,176.135594,Fruiting,Melicytus ramiflorus,Māhoe,197063,131,15.0
4,273582061,2025-04-26 11:16:37,-36.810763,174.943681,Flowering,Melicytus ramiflorus,Māhoe,197063,116,15.0
5,277585585,2025/04/26 10:05 AM,-43.579545,172.633167,Fruiting,Melicytus ramiflorus,Māhoe,197063,116,15.0
6,272136460,2025-04-22 17:13:17,-43.619107,172.650201,Fruiting,Melicytus ramiflorus,Māhoe,197063,112,15.0
7,272034640,2025-04-21 21:10:51,-38.517022,175.582863,Fruiting,Melicytus ramiflorus,Māhoe,197063,111,15.0
8,279300214,2025-04-18 12:45:40,-41.298378,174.010819,Fruiting,Melicytus ramiflorus,Māhoe,197063,108,15.0
9,277671049,2025-04-06 14:15:39+12:00,-45.842037,170.660478,Fruiting,Melicytus ramiflorus,Māhoe,197063,96,15.0
10,265513026,2025-03-16 14:02:45+13:00,-38.516995,175.582903,Fruiting,Melicytus ramiflorus,Māhoe,197063,75,15.0
11,266063589,2025/03/16 12:53 PM,-43.701831,172.698258,Flowering,Melicytus ramiflorus,Māhoe,197063,75,15.0
12,265325651,2025-03-15 10:42:15+13:00,-43.610250,172.642307,Fruiting,Melicytus ramiflorus,Māhoe,197063,73,15.0
13,264877164,2025-03-11 09:18:24+13:00,-40.729103,172.672438,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
14,264754904,2025-03-10 15:10:52+13:00,-43.627333,172.730255,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
15,264856087,2025/03/10 1:30 PM,-41.430072,172.995075,Fruiting,Melicytus ramiflorus,Māhoe,197063,69,15.0
16,265363303,2025/03/09 2:31 PM,-43.784035,172.834154,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
17,265027851,2025-03-09 12:24:25,-41.105044,175.078232,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
18,264709531,2025/03/09 10:55 AM,-43.649333,172.769439,Fruiting,Melicytus ramiflorus,Māhoe,197063,68,15.0
19,264331153,2025-03-04 09:39:54+13:00,-40.992080,173.012039,Fruiting,Melicytus ramiflorus,Māhoe,197063,62,15.0
20,263589406,2025-03-02 16:50:17,-41.334454,173.054780,Fruiting,Melicytus ramiflorus,Māhoe,197063,61,15.0
21,263587253,2025-03-02 12:08:41,-41.275132,173.731710,Fruiting,Melicytus ramiflorus,Māhoe,197063,61,15.0
22,267803871,2025/03/01 3:08 PM,-43.667441,172.788682,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
23,263448520,2025-03-01 13:34:14,-41.318110,174.204163,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
24,263799004,2025-03-01 10:25:53,-40.956967,173.059097,Fruiting,Melicytus ramiflorus,Māhoe,197063,60,15.0
25,288834336,2025/02/27 22:18,-40.851206,172.824000,Fruiting,Melicytus ramiflorus,Māhoe,197063,58,15.0
26,263118759,2025/02/26 4:11 PM,-41.240185,174.944166,Flowering,Melicytus ramiflorus,Māhoe,197063,57,15.0
27,263029257,2025-02-25 16:11:45+13:00,-43.524462,172.655930,Fruiting,Melicytus ramiflorus,Māhoe,197063,56,15.0
28,263029424,2025-02-25 15:48:14+13:00,-43.524478,172.655900,Fruiting,Melicytus ramiflorus,Māhoe,197063,56,15.0
29,261940788,2025-02-17 13:24:28,-37.245290,175.819730,Fruiting,Melicytus ramiflorus,Māhoe,197063,48,15.0

In [57]:
# mergeing the two data sets 
plant = pd.concat([dfa,dfb], axis=0, ignore_index=True)
plant.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025/09/22 1:15 PM,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22 14:11:58,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22 14:10:16+02:00,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22 13:51:14,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22 11:16:34,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
5,315797416,2025/09/22 10:24 AM,53.015837,-1.217560,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
6,315889887,2025/09/22 9:49 AM,52.633048,-2.159995,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
7,315796359,2025-09-21 13:47:52,38.693507,-111.680819,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
8,315692619,2025-09-21 14:36:17,42.952977,-81.220301,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
9,315575227,2025-09-21 14:11:03,61.149895,-45.514545,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
10,315576254,2025-09-21 12:59:04,61.151178,-45.517288,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
11,315777458,2025-09-21 12:48:22,61.154564,-45.517339,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
12,315848241,2025-09-21 16:37:08,64.061917,24.519427,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
13,315581490,2025-09-21 12:16:07,61.149258,-45.514995,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
14,315613849,2025-09-21 13:22:54+01:00,52.045803,0.720892,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
15,315595331,2025-09-21 12:30:19+02:00,61.154842,-45.517208,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
16,315499597,2025-09-21 08:57:12,56.004232,-2.517871,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
17,315711373,2025-09-19 15:32:48-04:00,39.062970,-79.323775,Flowering,Achillea millefolium,common yarrow,52821,262,26.0
18,314760899,2025-09-18 08:32:58,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,261,15.0
19,314671810,2025-09-17 13:28:46,46.793167,-121.729866,Flowering,Achillea millefolium,common yarrow,52821,260,19.0
20,314881060,2025/09/17 11:33 AM,45.848500,-123.961264,Flowering,Achillea millefolium,common yarrow,52821,260,9.0
21,314877257,2025/09/17 11:32 AM,45.848278,-123.961350,Fruiting,Achillea millefolium,common yarrow,52821,260,9.0
22,314624633,2025-09-17 18:18:21,53.208419,-6.114972,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
23,314544453,2025-09-17 10:57:57,51.462255,-0.065373,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
24,314477944,2025-09-16 17:55:04,41.622425,-70.537878,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
25,314420251,2025-09-16 12:47:35-07:00,49.254517,-123.002242,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
26,314435157,2025-09-16 18:03:34,47.995943,7.833229,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
27,314343934,2025-09-16 16:44:04,65.034488,25.454223,Flowering,Achillea millefolium,common yarrow,52821,259,27.0
28,314279893,2025-09-16 06:23:51,51.532009,-0.286650,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
29,314242933,2025-09-15 18:47:19-04:00,39.725803,-76.076722,Flowering,Achillea millefolium,common yarrow,52821,258,14.0

In [37]:
plant.shape

(758759, 10)

In [56]:
counts=plant['scientific_name'].value_counts()
count_freq=counts.reset_index()
count_freq.columns = ['scientific_name', 'frequency']
count_freq = count_freq.sort_values(by='frequency', ascending=True)
count_freq.head(300)

             scientific_name  frequency
900              Jarava ichu          3
899  Kalanchoe blossfeldiana          4
898   Vachellia xanthophloea          5
897     Agave cordillerensis          6
896          Celtis africana          9
..                       ...        ...
605         Acacia fimbriata        299
604      Cordyline australis        299
603    Dichrostachys cinerea        305
602      Grewia occidentalis        306
601      Hypericum gramineum        307

[300 rows x 2 columns]

In [58]:
import pandas as pd
import re

# Example: ensure column is string
plant['observed_on'] = plant['observed_on'].astype(str)

# Extract only the date portion using regex
plant['observed_on'] = plant['observed_on'].apply(
    lambda x: re.search(r'\d{4}[-/]\d{2}[-/]\d{2}', x).group(0) if re.search(r'\d{4}[-/]\d{2}[-/]\d{2}', x) else x
)

# Standardize format (replace '/' with '-')
plant['observed_on'] = plant['observed_on'].str.replace('/', '-', regex=False)

In [59]:
plant.head(30)

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome
0,315987576,2025-09-22,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
1,315797997,2025-09-22,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
2,316026631,2025-09-22,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0
3,315784690,2025-09-22,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
4,315774789,2025-09-22,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
5,315797416,2025-09-22,53.015837,-1.217560,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
6,315889887,2025-09-22,52.633048,-2.159995,Flowering,Achillea millefolium,common yarrow,52821,265,15.0
7,315796359,2025-09-21,38.693507,-111.680819,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
8,315692619,2025-09-21,42.952977,-81.220301,Flowering,Achillea millefolium,common yarrow,52821,264,26.0
9,315575227,2025-09-21,61.149895,-45.514545,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
10,315576254,2025-09-21,61.151178,-45.517288,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
11,315777458,2025-09-21,61.154564,-45.517339,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
12,315848241,2025-09-21,64.061917,24.519427,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
13,315581490,2025-09-21,61.149258,-45.514995,Flowering,Achillea millefolium,common yarrow,52821,264,29.0
14,315613849,2025-09-21,52.045803,0.720892,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
15,315595331,2025-09-21,61.154842,-45.517208,Flowering,Achillea millefolium,common yarrow,52821,264,27.0
16,315499597,2025-09-21,56.004232,-2.517871,Flowering,Achillea millefolium,common yarrow,52821,264,15.0
17,315711373,2025-09-19,39.062970,-79.323775,Flowering,Achillea millefolium,common yarrow,52821,262,26.0
18,314760899,2025-09-18,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,261,15.0
19,314671810,2025-09-17,46.793167,-121.729866,Flowering,Achillea millefolium,common yarrow,52821,260,19.0
20,314881060,2025-09-17,45.848500,-123.961264,Flowering,Achillea millefolium,common yarrow,52821,260,9.0
21,314877257,2025-09-17,45.848278,-123.961350,Fruiting,Achillea millefolium,common yarrow,52821,260,9.0
22,314624633,2025-09-17,53.208419,-6.114972,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
23,314544453,2025-09-17,51.462255,-0.065373,Flowering,Achillea millefolium,common yarrow,52821,260,15.0
24,314477944,2025-09-16,41.622425,-70.537878,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
25,314420251,2025-09-16,49.254517,-123.002242,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
26,314435157,2025-09-16,47.995943,7.833229,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
27,314343934,2025-09-16,65.034488,25.454223,Flowering,Achillea millefolium,common yarrow,52821,259,27.0
28,314279893,2025-09-16,51.532009,-0.286650,Flowering,Achillea millefolium,common yarrow,52821,259,15.0
29,314242933,2025-09-15,39.725803,-76.076722,Flowering,Achillea millefolium,common yarrow,52821,258,14.0

In [62]:

conditions = [
    (plant['biome'].between(1, 5)),
    (plant['biome'].between(6, 8)),
    (plant['biome'].between(9, 14)),
    (plant['biome'].between(15, 21)),
    (plant['biome'].between(22, 24)),
    (plant['biome'] >= 25)
]

choices = ['A', 'B', 'C', 'D', 'E', 'H']

plant['biome_cat'] = np.select(conditions, choices, default='Unknown')

In [41]:
plant.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome,biome_cat
0,315987576,2025-09-22,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
1,315797997,2025-09-22,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
2,316026631,2025-09-22,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0,H
3,315784690,2025-09-22,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
4,315774789,2025-09-22,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D

In [70]:
species_counts = plant['scientific_name'].value_counts()

# 🔹 Step 3: Keep only species with >= 300 observations
valid_species = species_counts[species_counts >= 500].index

# 🔹 Step 4: Filter the dataset
filtered_plant = plant[plant['scientific_name'].isin(valid_species)].copy()
filtered_plant.head()

,id,observed_on,latitude,longitude,phenophase,scientific_name,common_name,taxon_id,doy,biome,biome_cat
0,315987576,2025-09-22,49.230847,-122.929039,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
1,315797997,2025-09-22,55.324646,-1.554149,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
2,316026631,2025-09-22,60.718503,-46.036708,Flowering,Achillea millefolium,common yarrow,52821,265,29.0,H
3,315784690,2025-09-22,48.200201,17.196155,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D
4,315774789,2025-09-22,50.773417,-3.999461,Flowering,Achillea millefolium,common yarrow,52821,265,15.0,D

In [71]:
filtered_plant.shape

(678400, 11)

In [72]:
filtered_plant['scientific_name'].nunique()

504

In [42]:
plant.drop(columns=['id','latitude','longitude','taxon_id'],inplace=True)

In [43]:
plant = plant[['biome','biome_cat', 'doy', 'scientific_name', 'common_name', 'phenophase']].dropna()

In [44]:
#Add cyclic encoding for DOY (so model understands seasonality)
plant['doy_sin'] = np.sin(2 * np.pi * plant['doy'] / 365)
plant['doy_cos'] = np.cos(2 * np.pi * plant['doy'] / 365)

In [45]:
plant.head()

,biome,biome_cat,doy,scientific_name,common_name,phenophase,doy_sin,doy_cos
0,15.0,D,265,Achillea millefolium,common yarrow,Flowering,-0.988678,-0.150055
1,15.0,D,265,Achillea millefolium,common yarrow,Flowering,-0.988678,-0.150055
2,29.0,H,265,Achillea millefolium,common yarrow,Flowering,-0.988678,-0.150055
3,15.0,D,265,Achillea millefolium,common yarrow,Flowering,-0.988678,-0.150055
4,15.0,D,265,Achillea millefolium,common yarrow,Flowering,-0.988678,-0.150055

In [49]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# 🧭 Suppose your dataframe is called plant and has these columns:
# ['biome_cat', 'doy', 'scientific_name', 'common_name', 'phenophase']

# Step 1: Encode biome_cat, species, and phenophase
enc_biome = LabelEncoder()
plant['biome_enc'] = enc_biome.fit_transform(plant['biome_cat'])

enc_species = LabelEncoder()
plant['species_enc'] = enc_species.fit_transform(plant['scientific_name'])

enc_phase = LabelEncoder()
plant['phase_enc'] = enc_phase.fit_transform(plant['phenophase'])

# Step 2: Add cyclic DOY features
plant['doy_sin'] = np.sin(2 * np.pi * plant['doy'] / 365)
plant['doy_cos'] = np.cos(2 * np.pi * plant['doy'] / 365)

# Step 3: Train species prediction model
X_species = plant[['biome_enc', 'doy_sin', 'doy_cos']]
y_species = plant['species_enc']

X_train, X_test, y_train, y_test = train_test_split(X_species, y_species, test_size=0.2, random_state=42)

model_species = RandomForestClassifier(n_estimators=300, random_state=42)
model_species.fit(X_train, y_train)

# Step 4: Train phenophase model (depends on biome, doy, and species)
X_phase = plant[['biome_enc', 'doy_sin', 'doy_cos', 'species_enc']]
y_phase = plant['phase_enc']

model_phase = RandomForestClassifier(n_estimators=300, random_state=42)
model_phase.fit(X_phase, y_phase)

# Step 5: Prediction function
def predict_species_phase(biome_cat, doy):
    # Convert inputs
    biome_enc = enc_biome.transform([biome_cat])[0]
    doy_sin = np.sin(2 * np.pi * doy / 365)
    doy_cos = np.cos(2 * np.pi * doy / 365)
    
    # Predict species
    species_code = model_species.predict([[biome_enc, doy_sin, doy_cos]])[0]
    species_name = enc_species.inverse_transform([species_code])[0]
    common_name = plant.loc[plant['scientific_name'] == species_name, 'common_name'].mode()[0]
    
    # Predict phenophase
    phase_code = model_phase.predict([[biome_enc, doy_sin, doy_cos, species_code]])[0]
    phase_name = enc_phase.inverse_transform([phase_code])[0]
    
    return {
        "biome_cat": biome_cat,
        "doy": doy,
        "scientific_name": species_name,
        "common_name": common_name,
        "phenophase": phase_name
    }

# 🔮 Example predictions
print(predict_species_phase("D", 120))
print(predict_species_phase("D", 265))
print(predict_species_phase("H", 300))

d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

{'biome_cat': 'D', 'doy': 120, 'scientific_name': 'Coprosma robusta', 'common_name': 'Karamū', 'phenophase': 'Fruiting'}

d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

{'biome_cat': 'D', 'doy': 265, 'scientific_name': 'Thysanotus patersonii', 'common_name': 'Twining Fringe-lily', 'phenophase': 'Flowering'}
{'biome_cat': 'H', 'doy': 300, 'scientific_name': 'Asclepias syriaca', 'common_name': 'common milkweed', 'phenophase': 'Fruiting'}

d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [48]:
result = pipeline.predict_top_n("A", 50, top_n=5)
print(result)

NameError: name 'pipeline' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model_species = RandomForestClassifier(
    n_estimators=100,   # smaller forest
    max_depth=15,       # shallower trees
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)
model_species.fit(X_train, y_train)

MemoryError: could not allocate 14761984 bytes

In [ ]:
ref_df = plant[['scientific_name', 'common_name']].drop_duplicates()
ref_df.to_csv("reference_names.csv", index=False)

In [ ]:
import joblib

joblib.dump(model_species, "model_species.pkl")
joblib.dump(model_phase, "model_phase.pkl")
joblib.dump(enc_biome, "enc_biome.pkl")
joblib.dump(enc_species, "enc_species.pkl")
joblib.dump(enc_phase, "enc_phase.pkl")

['enc_phase.pkl']

In [ ]:
# my_api.py
from fastapi import FastAPI
import joblib
import numpy as np
import pandas as pd

app = FastAPI()

# 🔹 Load models and reference table once at API startup
model_species = joblib.load("model_species.pkl")
model_phase = joblib.load("model_phase.pkl")
enc_biome = joblib.load("enc_biome.pkl")
enc_species = joblib.load("enc_species.pkl")
enc_phase = joblib.load("enc_phase.pkl")
ref_df = pd.read_csv("reference_names.csv")

# 🔹 Define endpoint
@app.get("/predict")
def predict(biome_cat: str, doy: int, top_n: int = 5):
    # Encode input
    biome_enc = enc_biome.transform([biome_cat])[0]
    doy_sin = np.sin(2*np.pi*doy/365)
    doy_cos = np.cos(2*np.pi*doy/365)

    # Species probabilities
    probs = model_species.predict_proba([[biome_enc, doy_sin, doy_cos]])[0]
    top_indices = np.argsort(probs)[::-1][:top_n]
    top_species = enc_species.inverse_transform(top_indices)

    # Common names
    top_common_names = [ref_df.loc[ref_df['scientific_name']==sp,'common_name'].values[0]
                        for sp in top_species]

    # Phenophase prediction
    X_phase = np.column_stack([np.repeat(biome_enc, top_n),
                               np.repeat(doy_sin, top_n),
                               np.repeat(doy_cos, top_n),
                               top_indices])
    phase_pred = model_phase.predict(X_phase)
    top_phenophases = enc_phase.inverse_transform(phase_pred)

    return {
        "biome_cat": biome_cat,
        "doy": doy,
        "top_species": list(top_species),
        "top_common_names": list(top_common_names),
        "top_phenophases": list(top_phenophases)
    }

MemoryError: could not allocate 27858920 bytes

### Evaluate scientific_name Prediction

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

# Accuracy
print("Species prediction accuracy:", accuracy_score(y_test, y_pred_species))

# Classification report with proper labels
labels = np.unique(y_test)  # only the species present in test set
target_names = enc_species.inverse_transform(labels)

print(classification_report(y_test, y_pred_species, labels=labels, target_names=target_names))

Species prediction accuracy: 0.054430913595866943
                               precision    recall  f1-score   support

              Acacia acinacea       0.00      0.00      0.00        45
               Acacia cyclops       0.00      0.00      0.00        38
              Acacia dealbata       0.05      0.03      0.04       207
             Acacia fimbriata       0.00      0.00      0.00        64
          Acacia genistifolia       0.00      0.00      0.00        80
             Acacia leiocalyx       0.00      0.00      0.00        35
            Acacia longifolia       0.00      0.00      0.00       212
              Acacia mearnsii       0.00      0.00      0.00        85
           Acacia melanoxylon       0.00      0.00      0.00       212
            Acacia myrtifolia       0.00      0.00      0.00       179
              Acacia paradoxa       0.00      0.00      0.00       137
             Acacia pycnantha       0.04      0.01      0.02       149
             Acacia retinodes       0.00      0.00      0.00        16
               Acacia saligna       0.00      0.00      0.00       112
            Acacia suaveolens       0.00      0.00      0.00       183
            Acacia terminalis       0.00      0.00      0.00       208
            Acacia ulicifolia       0.00      0.00      0.00       197
          Acacia verticillata       0.00      0.00      0.00       125
       Acaena novae-zelandiae       0.00      0.00      0.00        57
               Acer campestre       0.00      0.00      0.00        93
                 Acer negundo       0.07      0.02      0.03       817
             Acer platanoides       0.00      0.00      0.00       191
          Acer pseudoplatanus       0.00      0.00      0.00       118
                  Acer rubrum       0.03      0.03      0.03       505
             Acer saccharinum       0.10      0.02      0.04        91
               Acer saccharum       0.00      0.00      0.00        31
         Achillea millefolium       0.02      0.02      0.02       768
           Achyranthes aspera       0.00      0.00      0.00        32
           Acianthus pusillus       0.00      0.00      0.00       120
          Actinotus helianthi       0.00      0.00      0.00       200
           Adansonia digitata       0.05      0.04      0.05        25
        Aegopodium podagraria       0.00      0.00      0.00       198
       Aesculus hippocastanum       0.03      0.02      0.03       195
           Agapanthus praecox       0.00      0.00      0.00        44
              Agave americana       0.00      0.00      0.00        44
         Agave cordillerensis       0.00      0.00      0.00         1
          Ageratina altissima       0.06      0.23      0.09       800
          Agrimonia eupatoria       0.00      0.00      0.00       206
          Ailanthus altissima       0.04      0.01      0.01       355
                Ajuga reptans       0.08      0.21      0.12       200
         Allamanda cathartica       0.00      0.00      0.00        34
           Alliaria petiolata       0.04      0.09      0.06       803
            Allium triquetrum       0.00      0.00      0.00       202
               Allium ursinum       0.00      0.00      0.00       200
     Allocasuarina littoralis       0.00      0.00      0.00        64
   Allocasuarina verticillata       0.00      0.00      0.00        20
              Alnus acuminata       0.00      0.00      0.00         4
              Alnus glutinosa       0.08      0.03      0.05       129
             Aloe arborescens       0.00      0.00      0.00        83
                 Aloe davyana       0.00      0.00      0.00        15
                   Aloe ferox       0.13      0.45      0.21       214
               Aloe marlothii       0.00      0.00      0.00        29
                    Aloe vera       0.00      0.00      0.00        18
       Aloidendron dichotomum       0.08      0.17      0.11         6
           Alphitonia excelsa       0.00      0.00      0.00        33
            Alpinia purpurata       0.00      0.00      0.00        74
      Ambrosia artemisiifolia       0.00      0.00      0.00       231
             Ambrosia trifida       0.00      0.00      0.00       134
             Anacamptis morio       0.00      0.00      0.00       197
       Anacamptis pyramidalis       0.04      0.13      0.06       190
               Ananas comosus       0.00      0.00      0.00        38
       Anaphalis margaritacea       0.02      0.03      0.02       197
         Anemonoides nemorosa       0.10      0.21      0.13       199
    Anemonoides ranunculoides       0.00      0.00      0.00       210
          Angelica sylvestris       0.00      0.00      0.00       124
        Anthriscus sylvestris       0.00      0.00      0.00       205
         Anthurium andraeanum       0.00      0.00      0.00        13
         Anthyllis vulneraria       0.03      0.02      0.02       184
            Antirrhinum majus       0.00      0.00      0.00       153
          Apocynum cannabinum       0.00      0.00      0.00       209
         Aquilegia canadensis       0.04      0.06      0.05       215
           Aquilegia vulgaris       0.02      0.01      0.01       188
            Aralia nudicaulis       0.00      0.00      0.00       185
           Araujia sericifera       0.07      0.03      0.04       193
         Arctotheca calendula       0.00      0.00      0.00       198
           Argentina anserina       0.04      0.02      0.03       181
     Argyranthemum frutescens       0.00      0.00      0.00         8
          Arisaema triphyllum       0.05      0.05      0.05       835
          Aristotelia serrata       0.03      0.05      0.04        95
           Artemisia vulgaris       0.00      0.00      0.00       197
        Arthropodium strictum       0.00      0.00      0.00        85
               Arum maculatum       0.05      0.12      0.07       191
                 Arundo donax       0.02      0.05      0.03        58
        Asclepias curassavica       0.04      0.01      0.02       206
          Asclepias incarnata       0.00      0.00      0.00       222
            Asclepias syriaca       0.08      0.12      0.10       742
           Asclepias tuberosa       0.03      0.07      0.05       776
              Asimina triloba       0.05      0.03      0.04       193
       Asparagus asparagoides       0.00      0.00      0.00        22
           Asparagus capensis       0.00      0.00      0.00         8
         Asparagus rubicundus       0.00      0.00      0.00        10
            Asystasia intrusa       0.03      0.01      0.01       148
         Athanasia trifurcata       0.00      0.00      0.00        14
Austrocylindropuntia subulata       0.00      0.00      0.00        27
             Avicennia marina       0.04      0.02      0.02       120
          Baccharis latifolia       0.00      0.00      0.00         9
          Baccharis pilularis       0.07      0.07      0.07       185
           Banksia ericifolia       0.00      0.00      0.00        84
         Banksia integrifolia       0.00      0.00      0.00       121
            Banksia marginata       0.00      0.00      0.00       145
              Banksia serrata       0.00      0.00      0.00        72
            Banksia spinulosa       0.00      0.00      0.00       128
            Barbarea vulgaris       0.00      0.00      0.00       200
             Bauera rubioides       0.00      0.00      0.00        54
              Bellis perennis       0.07      0.17      0.10       190
         Berberis microphylla       0.00      0.00      0.00        44
          Berberis thunbergii       0.00      0.00      0.00       185
              Berteroa incana       0.00      0.00      0.00       212
          Berzelia lanuginosa       0.00      0.00      0.00         7
            Betula papyrifera       0.00      0.00      0.00        16
               Betula pendula       0.00      0.00      0.00        40
                  Bidens alba       0.05      0.20      0.09       205
              Bidens andicola       0.00      0.00      0.00         3
                Bidens pilosa       0.00      0.00      0.00       154
                Bixa orellana       0.00      0.00      0.00        64
            Boophone disticha       0.02      0.01      0.01       106
         Bougainvillea glabra       0.00      0.00      0.00        10
    Bougainvillea spectabilis       0.00      0.00      0.00         5
        Brachyglottis repanda       0.00      0.00      0.00        59
         Brachylaena discolor       0.00      0.00      0.00         7
         Breynia oblongifolia       0.00      0.00      0.00        32
                 Briza maxima       0.00      0.00      0.00       133
         Brugmansia sanguinea       0.00      0.00      0.00        16
           Brunonia australis       0.00      0.00      0.00        52
        Brunsvigia orientalis       0.00      0.00      0.00        40
             Buddleja davidii       0.00      0.00      0.00       207
             Buddleja saligna       0.11      0.13      0.12        82
         Buddleja salviifolia       0.00      0.00      0.00        20
              Bulbine bulbosa       0.00      0.00      0.00        49
         Burchardia umbellata       0.00      0.00      0.00       151
             Bursaria spinosa       0.01      0.01      0.01       201
      Caesalpinia pulcherrima       0.03      0.01      0.01       107
             Caladenia carnea       0.04      0.11      0.06       205
           Caladenia catenata       0.00      0.00      0.00        60
              Caladenia flava       0.03      0.12      0.05       103
            Caladenia fuscata       0.00      0.00      0.00        35
        Caladenia tentaculata       0.04      0.09      0.06       205
             Caladium bicolor       0.00      0.00      0.00         3
       Calamagrostis epigejos       0.00      0.00      0.00        95
                Caleana major       0.00      0.00      0.00       117
             Callianthe picta       0.00      0.00      0.00        40
         Callicarpa americana       0.04      0.39      0.07       784
             Calluna vulgaris       0.05      0.00      0.01       205
           Calotropis procera       0.03      0.01      0.01       182
             Caltha palustris       0.00      0.00      0.00       201
            Calystegia sepium       0.00      0.00      0.00       204
           Calytrix tetragona       0.00      0.00      0.00       127
             Campanula patula       0.00      0.00      0.00       194
       Campanula rotundifolia       0.00      0.00      0.00       181
             Campsis radicans       0.03      0.14      0.05       601
                 Canna indica       0.00      0.00      0.00       114
              Canna × hybrida       0.00      0.00      0.00         7
             Cantua buxifolia       0.00      0.00      0.00         6
      Capsella bursa-pastoris       0.00      0.00      0.00       210
        Cardamine concatenata       0.00      0.00      0.00       177
            Cardamine hirsuta       0.00      0.00      0.00       194
          Cardamine pratensis       0.01      0.01      0.01       192
                Carica papaya       0.05      0.04      0.04       141
            Carissa bispinosa       0.07      0.14      0.10        74
           Carissa macrocarpa       0.00      0.00      0.00        25
           Carnegiea gigantea       0.20      0.60      0.30       341
             Carpinus betulus       0.00      0.00      0.00        52
           Carpobrotus edulis       0.01      0.01      0.01       191
          Carpodetus serratus       0.00      0.00      0.00        33
          Castilleja arvensis       0.00      0.00      0.00       169
     Casuarina cunninghamiana       0.00      0.00      0.00         3
      Casuarina equisetifolia       0.00      0.00      0.00        30
          Catharanthus roseus       0.08      0.18      0.11       217
              Ceiba pentandra       0.00      0.00      0.00        36
               Ceiba speciosa       0.00      0.00      0.00        29
        Celastrus orbiculatus       0.08      0.20      0.11       855
            Cenchrus setaceus       0.06      0.03      0.04       117
             Centaurea cyanus       0.00      0.00      0.00       193
              Centaurea jacea       0.00      0.00      0.00       188
           Centaurea scabiosa       0.00      0.00      0.00       208
         Centaurium erythraea       0.00      0.00      0.00       214
            Centranthus ruber       0.00      0.00      0.00       207
    Cephalanthus occidentalis       0.03      0.05      0.04       796
            Cercis canadensis       0.05      0.17      0.07       809
               Cestrum parqui       0.00      0.00      0.00       169
     Chamaecrista fasciculata       0.00      0.00      0.00       198
   Chamaenerion angustifolium       0.04      0.34      0.08       787
       Chamaescilla corymbosa       0.02      0.01      0.01        96
            Chelidonium majus       0.00      0.00      0.00       194
            Chenopodium album       0.00      0.00      0.00        99
           Chenopodium nutans       0.00      0.00      0.00        24
          Chiloglottis valida       0.00      0.00      0.00        41
          Chimaphila maculata       0.05      0.21      0.08       834
           Chironia baccifera       0.00      0.00      0.00        49
         Chlorophytum comosum       0.00      0.00      0.00         6
    Chrysocephalum apiculatum       0.00      0.00      0.00        45
           Chrysocoma ciliata       0.00      0.00      0.00        42
            Cichorium intybus       0.01      0.00      0.00       847
              Cirsium arvense       0.04      0.03      0.03       835
              Cirsium vulgare       0.02      0.00      0.01       824
               Citrus × limon       0.00      0.00      0.00         2
          Claytonia virginica       0.06      0.21      0.10       823
            Clematis aristata       0.00      0.00      0.00        34
           Clematis brachiata       0.14      0.25      0.18        57
         Clematis microphylla       0.00      0.00      0.00       103
             Clematis vitalba       0.03      0.02      0.02       186
        Cliffortia ruscifolia       0.00      0.00      0.00         6
               Cocos nucifera       0.02      0.02      0.02       187
          Codiaeum variegatum       0.00      0.00      0.00         4
               Coffea arabica       0.00      0.00      0.00        40
       Coleus scutellarioides       0.00      0.00      0.00         7
           Colpoon compressum       0.00      0.00      0.00        48
          Comesperma ericinum       0.00      0.00      0.00        78
          Comesperma volubile       0.00      0.00      0.00        89
           Commelina africana       0.00      0.00      0.00        39
             Commelina cyanea       0.00      0.00      0.00        75
             Commelina erecta       0.04      0.13      0.06       223
             Conium maculatum       0.00      0.00      0.00       195
      Conoclinium coelestinum       0.00      0.00      0.00       190
          Convallaria majalis       0.14      0.07      0.10       208
         Convolvulus arvensis       0.00      0.00      0.00       211
         Coprosma grandifolia       0.00      0.00      0.00       142
           Coprosma propinqua       0.00      0.00      0.00        31
          Coprosma quadrifida       0.00      0.00      0.00        29
              Coprosma repens       0.00      0.00      0.00        70
          Coprosma rhamnoides       0.00      0.00      0.00        74
             Coprosma robusta       0.01      0.03      0.02       200
          Cordyline australis       0.00      0.00      0.00        68
          Cordyline fruticosa       0.00      0.00      0.00        10
          Coriaria ruscifolia       0.00      0.00      0.00         7
            Cornus canadensis       0.03      0.08      0.05       782
               Cornus florida       0.04      0.09      0.06       804
             Cornus sanguinea       0.00      0.00      0.00       210
               Cornus sericea       0.00      0.00      0.00       516
       Coronidium scorpioides       0.00      0.00      0.00        51
               Correa reflexa       0.00      0.00      0.00       174
   Corryocactus melanotrichus       0.00      0.00      0.00        73
          Cortaderia selloana       0.04      0.01      0.02       136
             Corydalis solida       0.06      0.03      0.04       198
             Corylus avellana       0.08      0.05      0.06       192
      Corynocarpus laevigatus       0.00      0.00      0.00        31
            Cosmos sulphureus       0.00      0.00      0.00       145
         Cotyledon orbiculata       0.00      0.00      0.00        86
           Crassula capitella       0.00      0.00      0.00        20
             Crassula muscosa       0.00      0.00      0.00         3
               Crassula ovata       0.00      0.00      0.00         9
           Crataegus monogyna       0.03      0.14      0.05       180
            Crescentia cujete       0.00      0.00      0.00        26
   Crocosmia × crocosmiiflora       0.01      0.01      0.01       191
             Cryptocarya alba       0.00      0.00      0.00        57
        Cryptostylis subulata       0.00      0.00      0.00       108
    Cupaniopsis anacardioides       0.00      0.00      0.00        22
          Cussonia paniculata       0.00      0.00      0.00         7
             Cussonia spicata       0.00      0.00      0.00         2
           Cymbalaria muralis       0.00      0.00      0.00       198
           Cyperus eragrostis       0.00      0.00      0.00       120
           Cypripedium acaule       0.08      0.45      0.13       786
            Cytisus scoparius       0.00      0.00      0.00       195
           Dactylis glomerata       0.06      0.08      0.07       191
         Dactylorhiza fuchsii       0.33      0.01      0.01       170
               Dahlia pinnata       0.00      0.00      0.00         5
               Dalea coerulea       0.00      0.00      0.00        13
             Dampiera stricta       0.00      0.00      0.00       124
            Datura stramonium       0.00      0.00      0.00       195
                Daucus carota       0.00      0.00      0.00       808
         Daviesia leptophylla       0.02      0.03      0.03       208
          Daviesia ulicifolia       0.07      0.04      0.05       206
                Delonix regia       0.05      0.04      0.04       137
            Dianella caerulea       0.00      0.00      0.00        42
            Dianella revoluta       0.00      0.00      0.00        60
   Dicerothamnus rhinocerotis       0.00      0.00      0.00         5
             Dichondra repens       0.00      0.00      0.00        19
        Dichrostachys cinerea       0.00      0.00      0.00        51
           Digitalis purpurea       0.03      0.04      0.03       205
            Dillwynia sericea       0.00      0.00      0.00        60
      Dimorphotheca pluvialis       0.00      0.00      0.00        17
       Diospyros dichrophylla       0.00      0.00      0.00        39
          Diospyros lycioides       0.00      0.00      0.00        64
         Diospyros virginiana       0.00      0.00      0.00       184
              Dipodium roseum       0.06      0.18      0.09       213
          Dipodium variegatum       0.02      0.10      0.04       182
            Dipsacus fullonum       0.00      0.00      0.00       206
      Dipterostemon capitatus       0.00      0.00      0.00       202
               Disa bracteata       0.05      0.03      0.03        78

d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Evaluate Phenophase Prediction

In [ ]:
X_phase_test = X_phase.iloc[y_test.index]  # match test set rows
y_phase_test = y_phase.iloc[y_test.index]

y_pred_phase = model_phase.predict(X_phase_test)

print("Phenophase prediction accuracy:", accuracy_score(y_phase_test, y_pred_phase))
print(classification_report(y_phase_test, y_pred_phase, target_names=enc_phase.classes_))

Phenophase prediction accuracy: 0.9185447308766935
              precision    recall  f1-score   support

     Budding       0.80      0.45      0.57      8871
   Flowering       0.92      0.97      0.95    106573
    Fruiting       0.92      0.88      0.90     36308

    accuracy                           0.92    151752
   macro avg       0.88      0.77      0.81    151752
weighted avg       0.92      0.92      0.91    151752

### top-5species-output evaluation

In [ ]:
def predict_top_n_species_phase_batch(X_input, top_n=5):
    """
    Efficient batch prediction for top-N species and their phenophase.
    
    Parameters:
        X_input : pd.DataFrame
            Must contain columns ['biome_enc', 'doy_sin', 'doy_cos'] for species prediction.
        top_n : int
            Number of top species to return per row.
            
    Returns:
        pd.DataFrame with columns:
        ['top_species', 'top_common_names', 'top_phenophases']
    """
    # ✅ Ensure proper column order
    X_input = X_input[['biome_enc', 'doy_sin', 'doy_cos']]
    
    # 1️⃣ Predict species probabilities for all rows at once
    probs = model_species.predict_proba(X_input)  # shape: (n_samples, n_species)
    
    # 2️⃣ Get top-N species indices
    top_n_indices = np.argsort(probs, axis=1)[:, -top_n:][:, ::-1]  # descending order
    
    # 3️⃣ Convert species indices to scientific names
    top_species_names = enc_species.inverse_transform(top_n_indices.flatten()).reshape(top_n_indices.shape)
    
    # 4️⃣ Get common names for top-N species
    top_common_names = []
    for row in top_species_names:
        common_row = [plant.loc[plant['scientific_name'] == sp, 'common_name'].mode()[0] for sp in row]
        top_common_names.append(common_row)
    
    # 5️⃣ Predict phenophase for top-1 species
    top1_codes = top_n_indices[:, 0]
    X_phase_batch = np.column_stack([
        X_input['biome_enc'],
        X_input['doy_sin'],
        X_input['doy_cos'],
        top1_codes
    ])
    phase_pred = model_phase.predict(X_phase_batch)
    phase_pred_names = enc_phase.inverse_transform(phase_pred)
    
    # 6️⃣ Build result DataFrame
    result = pd.DataFrame({
        'top_species': list(top_species_names),
        'top_common_names': top_common_names,
        'predicted_phenophase': phase_pred_names
    })
    
    return result

# Example usage: batch of 5 rows
X_example = X_species.iloc[:5]
predictions = predict_top_n_species_phase_batch(X_example, top_n=5)
print(predictions)

                                         top_species  \
0  [Thysanotus patersonii, Acacia melanoxylon, Gl...
1  [Thysanotus patersonii, Acacia melanoxylon, Gl...
2  [Symphyotrichum novae-angliae, Ageratina altis...
3  [Thysanotus patersonii, Acacia melanoxylon, Gl...
4  [Thysanotus patersonii, Acacia melanoxylon, Gl...

                                    top_common_names predicted_phenophase
0  [Twining Fringe-lily, blackwood, Waxlip Orchid...            Flowering
1  [Twining Fringe-lily, blackwood, Waxlip Orchid...            Flowering
2  [New England aster, white snakeroot, common bu...            Flowering
3  [Twining Fringe-lily, blackwood, Waxlip Orchid...            Flowering
4  [Twining Fringe-lily, blackwood, Waxlip Orchid...            Flowering

d:\Programing\Machine learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(